name: open_git
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.0+3
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.2"
  dio: "^2.1.7"
  connectivity: "^0.3.2"
  json_annotation: "^2.4.0"
  shared_preferences: "^0.4.3"
  markdown: "^2.0.3"
  flutter_markdown: "^0.2.0"
  cached_network_image: "^0.8.0"
  flutter_webview_plugin: "^0.3.5"
  photo_view: "^0.4.0"
  flutter_spinkit: "^3.1.0"
  flutter_redux: "^0.5.3"
  fluro: "^1.4.0"
  package_info: "^0.4.0+4"
  qr_flutter: "^2.1.0+55"
  permission_handler: "^3.1.0"
  rxdart: "^0.22.0"
  pull_to_refresh: "^1.1.6"
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^1.5.1"
  json_serializable: "^3.0.0"
  install_apk_plugin:
    path: install_apk_plugin


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - image/ic_launcher.png
    - image/ic_branch.png
    - image/ic_default_head.png
    - image/1f44d.png
    - image/1f44e.png
    - image/1f389.png
    - image/1f440.png
    - image/1f604.png
    - image/1f615.png
    - image/1f680.png
    - image/2764.png
    - image/ic_like.png
    - image/ic_comment.png
    - image/ic_star.png
    - image/ic_issue.png