name: open_git
description: A new Flutter Github application.
author: Yuzo
homepage: https://github.com/Yuzopro

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.5.0+7
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  #http
  dio: any
  #http
  connectivity: any
  #http
  json_annotation: any
  #markdown
  markdown: any
  #markdown
  flutter_markdown: any
  #redux
  flutter_redux: any
  #router
  fluro: any
  #app package info
  package_info: any
  #qr code
  qr_flutter: any
  #apply permission
  permission_handler: any
  # 数据库
  sqflite: any
  # 文件管理
  path_provider: any
  # 工具类
  flukit: any
  # 颜色选择器
  flutter_colorpicker: any
  # 红点
  badges: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  #####本地库
  install_apk_plugin:
    path: ./flutter_common_lib/install_apk_plugin
  flutter_base_ui:
    path: ./flutter_common_lib/flutter_base_ui
  flutter_common_util:
    path: ./flutter_common_lib/flutter_common_util


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  assets:
    - assets/data/language_colors.json
    - assets/data/home_data.json

    - assets/images/ic_launcher.png
    - assets/images/ic_branch.png
    - assets/images/ic_default_head.png
    - assets/images/comment/1f44d.png
    - assets/images/comment/1f44e.png
    - assets/images/comment/1f389.png
    - assets/images/comment/1f440.png
    - assets/images/comment/1f604.png
    - assets/images/comment/1f615.png
    - assets/images/comment/1f680.png
    - assets/images/comment/2764.png
    - assets/images/comment/ic_comment_edit.png
    - assets/images/comment/ic_comment_face.png
    - assets/images/comment/ic_comment_menu.png
    - assets/images/ic_like.png
    - assets/images/ic_comment.png
    - assets/images/ic_star.png
    - assets/images/ic_issue.png
    - assets/images/guide/bg_guide_home.png
    - assets/images/guide/bg_guide_repo_detail.png
    - assets/images/guide/bg_guide_issue_detail.png
    - assets/images/guide/bg_guide_theme.png
    - assets/images/bg_splash_ad.png
    - assets/images/ic_network_error.png
    - assets/images/ic_no_data.png
    - assets/images/ic_arrow_left_back.png
    - assets/images/profile/ic_profile_blog.png
    - assets/images/profile/ic_profile_company.png
    - assets/images/profile/ic_profile_email.png
    - assets/images/profile/ic_profile_location.png
    - assets/images/profile/ic_profile_csdn.png
    - assets/images/profile/ic_profile_juejin.png
    - assets/images/profile/ic_profile_jianshu.png
    - assets/images/profile/ic_profile_blog_small.png
    - assets/images/issue/ic_issue_label.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Icons
      fonts:
        - asset: assets/fonts/icons.ttf